### ISSUE TITLE
Clear playlist problem (er at least i think thats what the x is)

### ISSUE THREAD

**Issue by ClammyMantis488** [JoshuaDoes/zPlayer#2]
When you play a song, hit the X, then try and play another one, it'll give "Error: Variable subscript badly formatted." and crash.

**Comment by JoshuaDoes** [comment]
This is an issue I've come across a few times, and I will be releasing an update soon to fix it as I believe I've found the issue with it. It's just some simple derps with typing is all c:

**Comment by JoshuaDoes** [comment]
The issue has been fixed and will be noted in the changelog for Build 23
